name: Build Tauri

on:
  push:
jobs:
  build:
    name: "Test Build"

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            name: linux
            targets: "aarch64-apple-darwin,x86_64-apple-darwin"
            tauri_target: "universal-apple-darwin"
          - os: macos-latest
            name: mac
            targets: "aarch64-apple-darwin,x86_64-apple-darwin"
            tauri_target: "universal-apple-darwin"
          - os: windows-latest
            name: win
            targets: "aarch64-apple-darwin,x86_64-apple-darwin"
            tauri_target: "universal-apple-darwin"

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "yarn"
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './app/tauri -> target'
      - name: install dependencies (ubuntu only)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1 build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev javascriptcoregtk-4.1
      - name: Install NPM Packages
        run: |
          yarn install --immutable --network-timeout 120000
      - name: Build
        run: yarn build:tauri --verbose
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
      # Possibly set up some basic unit testing just to make sure parts render and none of the libraries are straight up breaking
      - uses: actions/upload-artifact@v2
        with:
          name: built-app-${{ matrix.name }}
# For now just upload the whole bundle, but we can be more specific later
          path: |
            app/tauri/target/release/bundle/**
#            app/tauri/target/release/bundle/deb/*.deb
#            app/tauri/target/release/bundle/appimage/*.AppImage
#            app/tauri/target/release/bundle/msi/*.msi
#            app/tauri/target/release/bundle/dmg/*.dmg
#            app/tauri/target/release/bundle/macos/*.app
